/* This file is autogenerated, do not edit*/
#include "ui_openMVG_control_points_registration_automoc.dir/moc_GraphicsMainWi_ZMAX4X32S5RHWY.cpp"
#include "ui_openMVG_control_points_registration_automoc.dir/moc_mainLayout_7TNVV2E43NC2NF.cpp"
